from flask import Flask
from configure import configure_app
from models import db, Room


def _default_rooms():
   #hotel rooms to seed.
   #maximum of 6 bedrooms max capacity 4 people per room. max beds 4 per room.
  
    return [
        {
            "id": "101",
            "room_type": "family",
            "capacity": 4,
            "price_per_night": 180.00,
            "bathrooms": 2,
            "beds": 3,
            "bedrooms": 2,
            "description": "Family room with two bedrooms and a shared living area.",
        },
        {
            "id": "201",
            "room_type": "family",
            "capacity": 5,
            "price_per_night": 220.00,
            "bathrooms": 2,
            "beds": 4,
            "bedrooms": 2,
            "description": "Spacious family suite with extra bed and balcony view.",
        },
        {
            "id": "110",
            "room_type": "double",
            "capacity": 2,
            "price_per_night": 130.00,
            "bathrooms": 1,
            "beds": 1,
            "bedrooms": 1,
            "description": "Standard double room ideal for couples.",
        },
        {
            "id": "120",
            "room_type": "single",
            "capacity": 1,
            "price_per_night": 95.00,
            "bathrooms": 1,
            "beds": 1,
            "bedrooms": 1,
            "description": "Compact single room with workspace.",
        },
        {
            "id": "301",
            "room_type": "suite",
            "capacity": 3,
            "price_per_night": 260.00,
            "bathrooms": 2,
            "beds": 2,
            "bedrooms": 1,
            "description": "Suite with lounge area and premium amenities.",
        },

        {
            "id": "305",
            "room_type": "suite",
            "capacity": 4,
            "price_per_night": 300.00,
            "bathrooms": 2,
            "beds": 3,
            "bedrooms": 2,
            "description": "Luxury suite with two bedrooms and city view.",
        },
        {
            "id": "130",
            "room_type": "single",
            "capacity": 1,
            "price_per_night": 90.00,
            "bathrooms": 1,
            "beds": 1,
            "bedrooms": 1,
            "description": "Economy single room with essential amenities.",
        },
        {
            "id": "210",
            "room_type": "double",
            "capacity": 2,
            "price_per_night": 140.00,
            "bathrooms": 1,
            "beds": 1,
            "bedrooms": 1,
            "description": "Deluxe double room with modern decor.",
        },
        {
            "id": "220",
            "room_type": "double",
            "capacity": 2,
            "price_per_night": 150.00,
            "bathrooms": 1,
            "beds": 2,
            "bedrooms": 1,
            "description": "Double room with two beds and garden view.",
        },
        {
            "id": "320",
            "room_type": "suite",
            "capacity": 3,
            "price_per_night": 280.00,
            "bathrooms": 2,
            "beds": 2,
            "bedrooms": 1,
            "description": "Executive suite with work area and premium services.",
        },
        {
            "id": "330",
            "room_type": "suite",
            "capacity": 4,
            "price_per_night": 320.00,
            "bathrooms": 2,
            "beds": 3,
            "bedrooms": 2,
            "description": "Presidential suite with luxurious amenities and panoramic views.",
        },
                {
            "id": "102",
            "room_type": "family",
            "capacity": 4,
            "price_per_night": 185.00,
            "bathrooms": 2,
            "beds": 3,
            "bedrooms": 2,
            "description": "Family room with bright interior and shared lounge.",
        },
        {
            "id": "103",
            "room_type": "family",
            "capacity": 4,
            "price_per_night": 190.00,
            "bathrooms": 2,
            "beds": 3,
            "bedrooms": 2,
            "description": "Family suite with kitchenette and courtyard view.",
        },
        {
            "id": "104",
            "room_type": "family",
            "capacity": 5,
            "price_per_night": 210.00,
            "bathrooms": 2,
            "beds": 4,
            "bedrooms": 3,
            "description": "Large family room with three bedrooms and extra living space.",
        },
        {
            "id": "105",
            "room_type": "family",
            "capacity": 5,
            "price_per_night": 225.00,
            "bathrooms": 2,
            "beds": 4,
            "bedrooms": 3,
            "description": "Comfortable family suite with modern furnishings.",
        },
        {
            "id": "106",
            "room_type": "family",
            "capacity": 4,
            "price_per_night": 200.00,
            "bathrooms": 2,
            "beds": 3,
            "bedrooms": 2,
            "description": "Cozy family room with balcony access.",
        },
        {
            "id": "107",
            "room_type": "family",
            "capacity": 5,
            "price_per_night": 230.00,
            "bathrooms": 2,
            "beds": 4,
            "bedrooms": 3,
            "description": "Spacious family suite with entertainment area.",
        },
        {
            "id": "108",
            "room_type": "family",
            "capacity": 4,
            "price_per_night": 195.00,
            "bathrooms": 2,
            "beds": 3,
            "bedrooms": 2,
            "description": "Family-style unit with outdoor seating.",
        },
        {
            "id": "111",
            "room_type": "double",
            "capacity": 2,
            "price_per_night": 135.00,
            "bathrooms": 1,
            "beds": 1,
            "bedrooms": 1,
            "description": "Double room with minimalist design.",
        },
        {
            "id": "112",
            "room_type": "double",
            "capacity": 2,
            "price_per_night": 145.00,
            "bathrooms": 1,
            "beds": 1,
            "bedrooms": 1,
            "description": "Double room offering city skyline views.",
        },
        {
            "id": "113",
            "room_type": "double",
            "capacity": 2,
            "price_per_night": 150.00,
            "bathrooms": 1,
            "beds": 2,
            "bedrooms": 1,
            "description": "Double room with twin beds and spacious layout.",
        },
        {
            "id": "114",
            "room_type": "double",
            "capacity": 2,
            "price_per_night": 155.00,
            "bathrooms": 1,
                       "beds": 1,
            "bedrooms": 1,
            "description": "Modern double room with premium lighting.",
        },
        {
            "id": "115",
            "room_type": "double",
            "capacity": 2,
            "price_per_night": 160.00,
            "bathrooms": 1,
            "beds": 2,
            "bedrooms": 1,
            "description": "Garden-facing double room with balcony.",
        },
        {
            "id": "116",
            "room_type": "double",
            "capacity": 2,
            "price_per_night": 152.00,
            "bathrooms": 1,
            "beds": 1,
            "bedrooms": 1,
            "description": "Double room with quiet interior for relaxation.",
        },
        {
            "id": "117",
            "room_type": "double",
            "capacity": 2,
            "price_per_night": 148.00,
            "bathrooms": 1,
            "beds": 1,
            "bedrooms": 1,
            "description": "Comfort double room with warm decor.",
        },
        {
            "id": "118",
            "room_type": "double",
            "capacity": 2,
            "price_per_night": 142.00,
            "bathrooms": 1,
            "beds": 1,
            "bedrooms": 1,
            "description": "Classic double room with office desk.",
        },
        {
            "id": "119",
            "room_type": "double",
            "capacity": 2,
            "price_per_night": 165.00,
            "bathrooms": 1,
            "beds": 2,
            "bedrooms": 1,
            "description": "Spacious double room with lounge area.",
        },
        {
            "id": "121",
            "room_type": "single",
            "capacity": 1,
            "price_per_night": 92.00,
            "bathrooms": 1,
            "beds": 1,
            "bedrooms": 1,
            "description": "Simple single room with modern workspace.",
        },
        {
            "id": "122",
            "room_type": "single",
            "capacity": 1,
            "price_per_night": 98.00,
            "bathrooms": 1,
            "beds": 1,
            "bedrooms": 1,
            "description": "Quiet single room ideal for business travelers.",
        },
        {
            "id": "123",
            "room_type": "single",
            "capacity": 1,
            "price_per_night": 100.00,
            "bathrooms": 1,
            "beds": 1,
            "bedrooms": 1,
            "description": "Minimalist single room with bright lighting.",
        },
        {
            "id": "124",
            "room_type": "single",
            "capacity": 1,
            "price_per_night": 105.00,
            "bathrooms": 1,
            "beds": 1,
            "bedrooms": 1,
            "description": "Cozy single room with premium bedding.",
        },
        {
            "id": "125",
            "room_type": "single",
            "capacity": 1,
            "price_per_night": 110.00,
            "bathrooms": 1,
            "beds": 1,
            "bedrooms": 1,
            "description": "Single room with compact storage solutions.",
        },
        {
            "id": "126",
            "room_type": "single",
            "capacity": 1,
            "price_per_night": 88.00,
            "bathrooms": 1,
            "beds": 1,
            "bedrooms": 1,
            "description": "Budget single room with essential comforts.",
        },
        {
            "id": "127",
            "room_type": "single",
            "capacity": 1,
            "price_per_night": 97.00,
            "bathrooms": 1,
            "beds": 1,
            "bedrooms": 1,
            "description": "Urban-style single room with compact desk.",
        },
        {
            "id": "128",
            "room_type": "single",
            "capacity": 1,
            "price_per_night": 102.00,
            "bathrooms": 1,
            "beds": 1,
            "bedrooms": 1,
            "description": "Single room featuring a comfortable reading nook.",
        },
        {
            "id": "129",
            "room_type": "single",
            "capacity": 1,
            "price_per_night": 112.00,
            "bathrooms": 1,
            "beds": 1,
            "bedrooms": 1,
            "description": "Premium single room with upgraded amenities.",
        },
        {
            "id": "302",
            "room_type": "suite",
            "capacity": 3,
            "price_per_night": 270.00,
            "bathrooms": 2,
            "beds": 2,
            "bedrooms": 1,
            "description": "Elegant suite with lounge and dining corner.",
        },
        {
            "id": "303",
            "room_type": "suite",
            "capacity": 4,
            "price_per_night": 295.00,
            "bathrooms": 2,
            "beds": 3,
            "bedrooms": 2,
            "description": "Two-bedroom suite with spacious living area.",
        },
        {
            "id": "304",
            "room_type": "suite",
            "capacity": 4,
            "price_per_night": 310.00,
            "bathrooms": 2,
            "beds": 3,
            "bedrooms": 2,
            "description": "Luxury suite with private balcony and lounge.",
        },
        {
            "id": "306",
            "room_type": "suite",
            "capacity": 3,
            "price_per_night": 255.00,
            "bathrooms": 2,
            "beds": 2,
            "bedrooms": 1,
            "description": "Comfort suite ideal for business travelers.",
        },
        {
            "id": "307",
            "room_type": "suite",
            "capacity": 4,
            "price_per_night": 325.00,
            "bathrooms": 2,
            "beds": 3,
            "bedrooms": 2,
            "description": "Upscale suite featuring modern interior design.",
        },
        {
            "id": "308",
            "room_type": "suite",
            "capacity": 4,
            "price_per_night": 340.00,
            "bathrooms": 2,
            "beds": 4,
            "bedrooms": 3,
            "description": "Three-bedroom suite with panoramic city views.",
        },
        {
            "id": "309",
            "room_type": "suite",
            "capacity": 4,
            "price_per_night": 350.00,
            "bathrooms": 2,
            "beds": 4,
            "bedrooms": 3,
            "description": "Luxury corner suite with entertainment center.",
        },
        {
            "id": "310",
            "room_type": "suite",
            "capacity": 3,
            "price_per_night": 265.00,
            "bathrooms": 2,
            "beds": 2,
            "bedrooms": 1,
            "description": "Suite with open layout and designer decor.",
        },
        {
            "id": "311",
            "room_type": "suite",
            "capacity": 4,
            "price_per_night": 300.00,
            "bathrooms": 2,
            "beds": 3,
            "bedrooms": 2,
            "description": "Two-bedroom suite with kitchenette and lounge.",
        },
        {
            "id": "312",
            "room_type": "suite",
            "capacity": 3,
            "price_per_night": 275.00,
            "bathrooms": 2,
            "beds": 2,
            "bedrooms": 1,
            "description": "Business suite with dedicated work area.",
        },
        {
            "id": "313",
            "room_type": "suite",
            "capacity": 4,
            "price_per_night": 305.00,
            "bathrooms": 2,
            "beds": 3,
            "bedrooms": 2,
            "description": "Contemporary suite with high-end finishes.",
        },
        {
            "id": "314",
            "room_type": "suite",
            "capacity": 4,
            "price_per_night": 330.00,
            "bathrooms": 2,
            "beds": 4,
            "bedrooms": 3,
            "description": "Large three-bedroom suite ideal for long stays.",
        },
        {
            "id": "315",
            "room_type": "suite",
            "capacity": 4,
            "price_per_night": 345.00,
            "bathrooms": 2,
            "beds": 4,
            "bedrooms": 3,
            "description": "Luxury suite with private meeting area.",
        },
        {
            "id": "316",
            "room_type": "suite",
            "capacity": 3,
            "price_per_night": 290.00,
            "bathrooms": 2,
            "beds": 2,
            "bedrooms": 1,
            "description": "Executive suite overlooking city gardens.",
        },
        {
            "id": "317",
            "room_type": "suite",
            "capacity": 3,
            "price_per_night": 285.00,
            "bathrooms": 2,
            "beds": 2,
            "bedrooms": 1,
            "description": "Comfort suite with elegant furnishing.",
        },
        {
            "id": "318",
            "room_type": "suite",
            "capacity": 4,
            "price_per_night": 320.00,
            "bathrooms": 2,
            "beds": 3,
            "bedrooms": 2,
            "description": "Two-bedroom suite with spacious dining area.",
        },
        {
            "id": "319",
            "room_type": "suite",
            "capacity": 4,
            "price_per_night": 360.00,
            "bathrooms": 2,
            "beds": 4,
            "bedrooms": 3,
            "description": "Ultra-premium suite with private terrace.",
        },
        {
            "id": "331",
            "room_type": "suite",
            "capacity": 4,
            "price_per_night": 355.00,
            "bathrooms": 2,
            "beds": 3,
            "bedrooms": 2,
            "description": "Designer suite with ambient lighting.",
        },
        {
            "id": "332",
            "room_type": "suite",
            "capacity": 4,
            "price_per_night": 370.00,
            "bathrooms": 2,
            "beds": 4,
            "bedrooms": 3,
            "description": "Executive luxury suite for premium guests.",
        },
        {
            "id": "333",
            "room_type": "suite",
            "capacity": 5,
            "price_per_night": 420.00,
            "bathrooms": 3,
            "beds": 4,
            "bedrooms": 4,
            "description": "High-end suite with four bedrooms and private lounge.",
        },
        {
            "id": "334",
            "room_type": "suite",
            "capacity": 5,
            "price_per_night": 450.00,
            "bathrooms": 3,
            "beds": 4,
            "bedrooms": 5,
            "description": "Grand suite with five bedrooms and luxury amenities.",
        },
        {
            "id": "335",
            "room_type": "suite",
            "capacity": 5,
            "price_per_night": 440.00,
            "bathrooms": 3,
            "beds": 4,
            "bedrooms": 4,
            "description": "Multi-room suite ideal for larger groups.",
        }

    ]


def seed_rooms(app: Flask | None = None):
    #Seed the rooms table with a default set of hotel rooms.
    
    app = app or Flask(__name__)
    configure_app(app)

    with app.app_context():
        db.create_all()
        existing_ids = {room.id for room in Room.query.with_entities(Room.id).all()}

        new_records = []
        for room_data in _default_rooms():
            if room_data["id"] in existing_ids:
                continue
            new_records.append(Room(**room_data, availability=True))

        if not new_records:
            print("Rooms already seeded; no changes made.")
            return

        db.session.add_all(new_records)
        db.session.commit()
        print(f"Seeded {len(new_records)} room(s).")


if __name__ == "__main__":
    seed_rooms()
